

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/navi-bar";
import { ThemeProvider } from "@/components/provider/theme-provider";
export const metadata: Metadata = {
  title: "alpha-assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" suppressHydrationWarning>
      <body className="h-screen w-screen flex flex-col justify-center items-center">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
              <Navbar/>
              {children}
          </ThemeProvider>
          
      </body>
    </html>
  );
}
