

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/navi-bar";
export const metadata: Metadata = {
  title: "alpha-assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" suppressHydrationWarning>
      <body className="h-screen w-screen flex flex-col justify-center items-center">
              <Navbar/>
              {children}
          
      </body>
    </html>
  );
}
